FROM ubuntu:bionic

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    accountsservice \
    acl \
    acpid \
    apparmor \
    apport \
    apport-symptoms \
    apt-utils \
    at \
    bash-completion \
    bc \
    bcache-tools \
    bind9-host \
    bsdmainutils \
    btrfs-progs \
    btrfs-tools \
    busybox-initramfs \
    busybox-static \
    byobu \
    ca-certificates \
    cloud-guest-utils \
    cloud-init \
    cloud-initramfs-copymods \
    cloud-initramfs-dyn-netconf \
    command-not-found \
    command-not-found-data \
    console-setup \
    console-setup-linux \
    cpio \
    cron \
    cryptsetup \
    cryptsetup-bin \
    curl \
    dbus \
    debconf-i18n \
    dirmngr \
    distro-info-data \
    dmeventd \
    dmidecode \
    dmsetup \
    dns-root-data \
    dnsmasq-base \
    dnsutils \
    dosfstools \
    eatmydata \
    ebtables \
    ed \
    eject \
    ethtool \
    file \
    fonts-ubuntu-console \
    friendly-recovery \
    ftp \
    fuse \
    gawk \
    gdisk \
    geoip-database \
    gettext-base \
    gir1.2-glib-2.0 \
    git \
    git-man \
    gnupg \
    gnupg-l10n \
    gnupg-utils \
    gpg \
    gpg-agent \
    gpg-wks-client \
    gpg-wks-server \
    gpgconf \
    gpgsm \
    groff-base \
    hdparm \
    htop \
    info \
    init \
    initramfs-tools \
    initramfs-tools-bin \
    initramfs-tools-core \
    install-info \
    iproute2 \
    iptables \
    iputils-ping \
    iputils-tracepath \
    irqbalance \
    isc-dhcp-client \
    isc-dhcp-common \
    iso-codes \
    kbd \
    keyboard-configuration \
    klibc-utils \
    krb5-locales \
    landscape-common \
    language-selector-common \
    less \
    libaccountsservice0 \
    libapt-inst2.0 \
    libasn1-8-heimdal \
    libassuan0 \
    libatm1 \
    libbind9-160 \
    libbsd0 \
    libcap2-bin \
    libcurl3-gnutls \
    libcurl4 \
    libdbus-1-3 \
    libdevmapper-event1.02.1 \
    libdns-export1100 \
    libdns1100 \
    libdrm-common \
    libdrm2 \
    libdumbnet1 \
    libeatmydata1 \
    libedit2 \
    libelf1 \
    liberror-perl \
    libestr0 \
    libevent-2.1-6 \
    libexpat1 \
    libfastjson4 \
    libfreetype6 \
    libfribidi0 \
    libfuse2 \
    libgdbm-compat4 \
    libgdbm5 \
    libgeoip1 \
    libgirepository-1.0-1 \
    libglib2.0-0 \
    libglib2.0-data \
    libgpm2 \
    libgssapi-krb5-2 \
    libgssapi3-heimdal \
    libhcrypto4-heimdal \
    libheimbase1-heimdal \
    libheimntlm0-heimdal \
    libhx509-5-heimdal \
    libicu60 \
    libip6tc0 \
    libiptc0 \
    libirs160 \
    libisc-export169 \
    libisc169 \
    libisccc160 \
    libisccfg160 \
    libisns0 \
    libk5crypto3 \
    libkeyutils1 \
    libklibc \
    libkrb5-26-heimdal \
    libkrb5-3 \
    libkrb5support0 \
    libksba8 \
    libldap-2.4-2 \
    libldap-common \
    liblocale-gettext-perl \
    liblvm2app2.2 \
    liblvm2cmd2.02 \
    liblwres160 \
    liblxc-common \
    liblxc1 \
    liblzo2-2 \
    libmagic-mgc \
    libmagic1 \
    libmnl0 \
    libmpdec2 \
    libmpfr6 \
    libmspack0 \
    libnetfilter-conntrack3 \
    libnewt0.52 \
    libnfnetlink0 \
    libnghttp2-14 \
    libnih1 \
    libnpth0 \
    libnss-systemd \
    libntfs-3g88 \
    libnuma1 \
    libpam-cap \
    libpam-systemd \
    libparted2 \
    libpcap0.8 \
    libpci3 \
    libperl5.26 \
    libpipeline1 \
    libplymouth4 \
    libpng16-16 \
    libpolkit-agent-1-0 \
    libpolkit-backend-1-0 \
    libpolkit-gobject-1-0 \
    libpopt0 \
    libpsl5 \
    libpython3-stdlib \
    libpython3.6 \
    libpython3.6-minimal \
    libpython3.6-stdlib \
    libreadline5 \
    libreadline7 \
    libroken18-heimdal \
    librtmp1 \
    libsasl2-2 \
    libsasl2-modules \
    libsasl2-modules-db \
    libsigsegv2 \
    libslang2 \
    libsqlite3-0 \
    libssl1.0.0 \
    libssl1.1 \
    libtext-charwidth-perl \
    libtext-iconv-perl \
    libtext-wrapi18n-perl \
    libunwind8 \
    libusb-1.0-0 \
    libutempter0 \
    libuv1 \
    libwind0-heimdal \
    libwrap0 \
    libx11-6 \
    libx11-data \
    libxau6 \
    libxcb1 \
    libxdmcp6 \
    libxext6 \
    libxml2 \
    libxmlsec1 \
    libxmlsec1-openssl \
    libxmuu1 \
    libxslt1.1 \
    libxtables12 \
    libyaml-0-2 \
    linux-image-virtual \
    locales \
    logrotate \
    lsb-release \
    lshw \
    lsof \
    ltrace \
    lvm2 \
    lxcfs \
    lxd \
    lxd-client \
    man-db \
    manpages \
    mdadm \
    mime-support \
    mlocate \
    mtr-tiny \
    multiarch-support \
    nano \
    ncurses-term \
    net-tools \
    netbase \
    netcat-openbsd \
    netplan.io \
    networkd-dispatcher \
    nplan \
    ntfs-3g \
    open-iscsi \
    open-vm-tools \
    openssh-client \
    openssh-server \
    openssh-sftp-server \
    openssl \
    overlayroot \
    parted \
    pastebinit \
    patch \
    pciutils \
    perl \
    perl-modules-5.26 \
    pinentry-curses \
    plymouth \
    plymouth-theme-ubuntu-text \
    policykit-1 \
    pollinate \
    popularity-contest \
    powermgmt-base \
    psmisc \
    publicsuffix \
    python-apt-common \
    python3 \
    python3-apport \
    python3-apt \
    python3-asn1crypto \
    python3-attr \
    python3-automat \
    python3-blinker \
    python3-certifi \
    python3-cffi-backend \
    python3-chardet \
    python3-click \
    python3-colorama \
    python3-commandnotfound \
    python3-configobj \
    python3-constantly \
    python3-cryptography \
    python3-dbus \
    python3-debconf \
    python3-debian \
    python3-distro-info \
    python3-distupgrade \
    python3-gdbm \
    python3-gi \
    python3-httplib2 \
    python3-hyperlink \
    python3-idna \
    python3-incremental \
    python3-jinja2 \
    python3-json-pointer \
    python3-jsonpatch \
    python3-jsonschema \
    python3-jwt \
    python3-markupsafe \
    python3-minimal \
    python3-netifaces \
    python3-newt \
    python3-oauthlib \
    python3-openssl \
    python3-pam \
    python3-pkg-resources \
    python3-problem-report \
    python3-pyasn1 \
    python3-pyasn1-modules \
    python3-requests \
    python3-requests-unixsocket \
    python3-serial \
    python3-service-identity \
    python3-six \
    python3-software-properties \
    python3-systemd \
    python3-twisted \
    python3-twisted-bin \
    python3-update-manager \
    python3-urllib3 \
    python3-yaml \
    python3-zope.interface \
    python3.6 \
    python3.6-minimal \
    readline-common \
    rsync \
    rsyslog \
    run-one \
    screen \
    shared-mime-info \
    snapd \
    software-properties-common \
    sosreport \
    squashfs-tools \
    ssh-import-id \
    strace \
    sudo \
    systemd \
    tcpdump \
    telnet \
    time \
    tmux \
    tzdata \
    ubuntu-advantage-tools \
    ubuntu-minimal \
    ubuntu-release-upgrader-core \
    ubuntu-server \
    ubuntu-standard \
    ucf \
    udev \
    ufw \
    uidmap \
    unattended-upgrades \
    update-manager-core \
    update-notifier-common \
    ureadahead \
    usbutils \
    uuid-runtime \
    vim \
    vim-common \
    vim-runtime \
    vim-tiny \
    wget \
    whiptail \
    xauth \
    xdelta3 \
    xdg-user-dirs \
    xfsprogs \
    xkb-data \
    xxd \
    xz-utils \
    zerofree \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

RUN echo "root:passworD1" | chpasswd
